const categories=[{name:'Natura',image:'assets/aurora.jpg',subtitle:'Paesaggi che emozionano'},{name:'Spazio',image:'assets/nebula.jpg',subtitle:'Oltre ogni confine'},{name:'Minimal',image:'assets/dunes.jpg',subtitle:'La bellezza del silenzio'},{name:'Astratti',image:'assets/solar.jpg',subtitle:'Forme e colori'},{name:'Originali Drive',image:'assets/aurora.jpg',subtitle:'La tua collezione'}];
let wallpapers=[],selected='Tutti',term='',active=null;let favs=new Set(JSON.parse(localStorage.getItem('duo-favs')||'[]'));
const $=id=>document.getElementById(id);const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function catFor(w){return w.category==='Da classificare'?'Originali Drive':w.category}
function hasLocal(w){return !w.driveId} // Drive originals are referenced but not embedded until imported
function imagePath(w){return w.image}
function toggleFav(id){if(favs.has(id))favs.delete(id);else favs.add(id);localStorage.setItem('duo-favs',JSON.stringify([...favs]));render();if(active?.id===id)refreshHeart()}
function card(w){let local=hasLocal(w);let article=document.createElement('article');article.className='wall-card';article.innerHTML=`<button class="wall-preview" aria-label="Apri ${esc(w.title)}">${local?`<img loading="lazy" src="${esc(imagePath(w))}" alt="${esc(w.title)}">`:`<div class="missing">✦<br>${esc(w.title)}<br><small>Da Google Drive · apri per visualizzare</small></div>`}<span class="tag">${esc(catFor(w))}</span></button><button class="heart ${favs.has(w.id)?'liked':''}" aria-label="${favs.has(w.id)?'Rimuovi dai':'Aggiungi ai'} preferiti">${favs.has(w.id)?'♥':'♡'}</button><div class="wall-info"><div><strong>${esc(w.title)}</strong><small>${esc(w.source||'DUO Studio')}</small></div><span class="card-arrow">↗</span></div>`;article.querySelector('.wall-preview').onclick=()=>openDetail(w);article.querySelector('.heart').onclick=()=>toggleFav(w.id);return article}
function render(){const filtered=wallpapers.filter(w=>(selected==='Tutti'||catFor(w)===selected)&&(w.title+' '+catFor(w)).toLowerCase().includes(term));$('gallery').replaceChildren(...filtered.map(card));$('results').textContent=filtered.length+' sfondi';$('empty').hidden=filtered.length!==0;const favourites=wallpapers.filter(w=>favs.has(w.id));$('fav-gallery').replaceChildren(...favourites.map(card));$('fav-empty').hidden=favourites.length>0;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('selected',b.dataset.filter===selected))}
function setFilter(name){selected=name;render();document.querySelector('#galleria').scrollIntoView({behavior:'smooth'})}
function refreshHeart(){$('detail-heart').textContent=favs.has(active.id)?'♥ Nei preferiti':'♡ Salva nei preferiti'}
function openDetail(w){active=w;const local=hasLocal(w);$('detail-title').textContent=w.title;$('detail-category').textContent=catFor(w);$('detail-description').textContent=local?'Uno sfondo originale della collezione DUO Studio. Pensato per uno schermo immersivo.':'Questo sfondo fa parte della tua collezione privata Google Drive.';$('detail-source').textContent=w.source;$('detail-resolution').textContent=local?'2160 × 3840 · 4K':'File originale';$('detail-img').hidden=!local;$('detail-fallback').hidden=local;if(local)$('detail-img').src=w.image;const d=$('download');d.href=local?w.image:'https://drive.google.com/file/d/'+encodeURIComponent(w.driveId)+'/view';d.textContent=local?'↓ Scarica in 4K':'↗ Apri su Google Drive';if(local){d.setAttribute('download',w.filename||w.title+'.jpg');d.target='_self'}else{d.removeAttribute('download');d.target='_blank';d.rel='noopener noreferrer'}$('detail-note').textContent=local?'Puoi scaricare il file originale direttamente. Su iPhone, apri il file e salvalo in Foto.':'I file originali di Drive non sono inclusi nello ZIP per motivi di accesso. Per mostrarli direttamente sul sito, copia i file nella cartella originals/ e segui README.md.';refreshHeart();$('detail').showModal()}
$('close').onclick=()=>$('detail').close();$('detail').addEventListener('click',e=>{if(e.target===$('detail'))$('detail').close()});$('detail-heart').onclick=()=>toggleFav(active.id);$('search').addEventListener('input',e=>{term=e.target.value.toLowerCase().trim();render();if(term)document.querySelector('#galleria').scrollIntoView({behavior:'smooth'})});$('theme').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('duo-theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('duo-theme')==='light')document.body.classList.add('light');$('reset').onclick=()=>{selected='Tutti';term='';$('search').value='';render()};
fetch('wallpapers.json').then(r=>{if(!r.ok)throw Error('Catalogo non disponibile');return r.json()}).then(data=>{wallpapers=data;$('total-count').textContent=data.length;const cats=['Tutti',...categories.map(c=>c.name)];$('filters').replaceChildren(...cats.map(name=>{const b=document.createElement('button');b.className='filter';b.dataset.filter=name;b.textContent=name;b.onclick=()=>setFilter(name);return b}));$('category-grid').replaceChildren(...categories.map(c=>{let b=document.createElement('button');b.className='category-card';b.innerHTML=`<img loading="lazy" alt="" src="${c.image}"><span class="category-label">${c.name}<small>${c.subtitle}</small></span>`;b.onclick=()=>setFilter(c.name);return b}));render()}).catch(err=>{$('gallery').textContent='Errore di caricamento: '+err.message+'. Pubblica su GitHub Pages o usa un server locale.'});
