const categories=[{name:'Animali',image:'originals/wildlife-leone-savana.jpg',subtitle:'La natura, libera'},{name:'Natura',image:'originals/Matterhorn%2001.png',subtitle:'Paesaggi che emozionano'},{name:'Paesaggi',image:'originals/97A233FF-D5C5-44C3-B746-6B9283F49172.JPG',subtitle:'Luoghi da esplorare'}];
let wallpapers=[],selected='Tutti',term='',active=null;let favs=new Set(JSON.parse(localStorage.getItem('duo-favs')||'[]'));
const $=id=>document.getElementById(id);const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function catFor(w){return w.category||''}
function hasLocal(w){return true}
function imagePath(w){return w.image}
function toggleFav(id){if(favs.has(id))favs.delete(id);else favs.add(id);localStorage.setItem('duo-favs',JSON.stringify([...favs]));render();if(active?.id===id)refreshHeart()}
function card(w){let local=hasLocal(w);let article=document.createElement('article');article.className='wall-card';article.innerHTML=`<button class="wall-preview" aria-label="Apri ${esc(w.title)}"><img loading="lazy" src="${esc(imagePath(w))}" alt="${esc(w.title)}">${w.category?`<span class="tag">${esc(catFor(w))}</span>`:''}</button><button class="heart ${favs.has(w.id)?'liked':''}" aria-label="${favs.has(w.id)?'Rimuovi dai':'Aggiungi ai'} preferiti">${favs.has(w.id)?'♥':'♡'}</button><div class="wall-info"><div><strong>${esc(w.title)}</strong><small>${esc(w.source||'DUO Studio')}</small></div><span class="card-arrow">↗</span></div>`;article.querySelector('.wall-preview').onclick=()=>openDetail(w);article.querySelector('.heart').onclick=()=>toggleFav(w.id);return article}
function render(){const filtered=wallpapers.filter(w=>(selected==='Tutti'||catFor(w)===selected)&&(w.title+' '+catFor(w)).toLowerCase().includes(term));$('gallery').replaceChildren(...filtered.map(card));$('results').textContent=filtered.length+' sfondi';$('empty').hidden=filtered.length!==0;const favourites=wallpapers.filter(w=>favs.has(w.id));$('fav-gallery').replaceChildren(...favourites.map(card));$('fav-empty').hidden=favourites.length>0;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('selected',b.dataset.filter===selected))}
function setFilter(name){selected=name;render();document.querySelector('#galleria').scrollIntoView({behavior:'smooth'})}
function refreshHeart(){$('detail-heart').textContent=favs.has(active.id)?'♥ Nei preferiti':'♡ Salva nei preferiti'}
function openDetail(w){active=w;$('detail-title').textContent=w.title;$('detail-category').textContent=catFor(w)||'DUO Wallpapers';$('detail-description').textContent=w.description||'Uno sfondo della collezione DUO Wallpapers. Pensato per uno schermo immersivo.';$('detail-source').textContent=w.source;$('detail-resolution').textContent=w.width+' × '+w.height+(w.generated?' · Alta definizione':' · File originale');$('detail-img').hidden=false;$('detail-fallback').hidden=true;$('detail-img').src=w.image;$('detail-img').style.objectFit='contain';const d=$('download');d.href=w.image;d.textContent=w.generated?'↓ Scarica wallpaper':'↓ Scarica originale';d.setAttribute('download',w.filename||w.title+'.jpg');d.target='_self';$('detail-note').textContent='Scarica il file originale direttamente dal sito. Su iPhone, apri il file e salvalo in Foto.';refreshHeart();$('detail').showModal()}
$('close').onclick=()=>$('detail').close();$('detail').addEventListener('click',e=>{if(e.target===$('detail'))$('detail').close()});$('detail-heart').onclick=()=>toggleFav(active.id);$('search').addEventListener('input',e=>{term=e.target.value.toLowerCase().trim();render();if(term)document.querySelector('#galleria').scrollIntoView({behavior:'smooth'})});$('theme').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('duo-theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('duo-theme')==='light')document.body.classList.add('light');$('reset').onclick=()=>{selected='Tutti';term='';$('search').value='';render()};
fetch('wallpapers.json?v=categories-2').then(r=>{if(!r.ok)throw Error('Catalogo non disponibile');return r.json()}).then(data=>{wallpapers=data;$('total-count').textContent=data.length;const cats=['Tutti',...categories.map(c=>c.name)];$('filters').replaceChildren(...cats.map(name=>{const b=document.createElement('button');b.className='filter';b.dataset.filter=name;b.textContent=name;b.onclick=()=>setFilter(name);return b}));$('category-grid').replaceChildren(...categories.map(c=>{let b=document.createElement('button');b.className='category-card';b.innerHTML=`<img loading="lazy" alt="Anteprima categoria ${esc(c.name)}" src="${c.image}"><span class="category-label">${c.name}<small>${c.subtitle}</small></span>`;b.onclick=()=>setFilter(c.name);return b}));render()}).catch(err=>{$('gallery').textContent='Errore di caricamento: '+err.message+'. Pubblica su GitHub Pages o usa un server locale.'});

/* Live lock screen: use the visitor's device time and local timezone. */
function updateDeviceClock(){
  const now=new Date();
  const time=new Intl.DateTimeFormat('it-CH',{hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(now);
  document.querySelectorAll('[data-device-time]').forEach(el=>{el.textContent=time;el.setAttribute('datetime',now.toISOString())});
  const date=document.querySelector('[data-device-date]');
  if(date){date.textContent=new Intl.DateTimeFormat('it-CH',{weekday:'long',day:'numeric',month:'long'}).format(now);date.setAttribute('datetime',now.toISOString().slice(0,10))}
}
updateDeviceClock();
setInterval(updateDeviceClock,1000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)updateDeviceClock()});
window.addEventListener('pageshow',updateDeviceClock);
